apiVersion: apps/v1
kind: DaemonSet
# In case more than one pod is required on each node, I'd use Deployment instead of DaemonSet
metadata:
  name: crud-rest-api
  namespace: crud-rest-api
  labels:
    app: crud-rest-api
spec:
  selector:
    matchLabels:
      name: crud-rest-api 
      app: crud-rest-api
  template:
    metadata:
      labels:
        name: crud-rest-api
        app: crud-rest-api
    spec:
      containers:
        - name: crud-rest-api
          image: nirbo2/crud-rest-api-flinks:57af2d92f31e362175e91161d7a32d001aeec12f
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
