apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: crud-rest-api-ingress
  namespace: crud-rest-api
spec:
  rules:
     - host: newcomers-api.internal.fin.ag
       http:
         paths:
           - backend:
               serviceName: crud-rest-api
               servicePort: 8080
             path: /persons
