apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  name: nginx-web-server-ingress
  namespace: flinks
spec:
  rules:
     - host: newcomers.internal.fin.ag
       http:
         paths:
           - backend:
               serviceName: nginx-web-server
               servicePort: 80
             path: /
